<?php
     
    $atualizar = new \Spw\Componentes\Mysql\AtualizarRegistro();
    $atualizar->Set_Conectar();
    $atualizar->Set_Start('POST', 'submit');
    $atualizar->Set_NomeDaTabela('spw_post_type');
    $atualizar->Set_ChavePrimaria('id_post_type', $_POST['id_post_type']);
    $atualizar->Set_Mensagem('Post Type atualizado com sucesso!');
    $atualizar->Set_AdicionarCampo(true, 'lixeira', 'string', 'value', 'N');
    $atualizar->Set_AdicionarCampo(true, 'post_type', 'string', 'post', 'post_type');
    $atualizar->Set_AdicionarCampo(true, 'public', 'string', 'post', 'public');
    $atualizar->Set_AdicionarCampo(true, 'publicly_queryable', 'string', 'post', 'publicly_queryable');
    $atualizar->Set_AdicionarCampo(true, 'show_ui', 'string', 'post', 'show_ui');
    $atualizar->Set_AdicionarCampo(true, 'show_in_menu', 'string', 'post', 'show_in_menu');
    $atualizar->Set_AdicionarCampo(true, 'show_in_nav_menus', 'string', 'post', 'show_in_nav_menus');
    $atualizar->Set_AdicionarCampo(true, 'show_in_admin_bar', 'string', 'post', 'show_in_admin_bar');
    $atualizar->Set_AdicionarCampo(true, 'menu_position', 'int', 'post', 'menu_position');
    $atualizar->Set_AdicionarCampo(true, 'menu_icon', 'string', 'post', 'menu_icon');
    $atualizar->Set_AdicionarCampo(true, 'capability_type', 'string', 'post', 'capability_type');
    $atualizar->Set_AdicionarCampo(true, 'hierarchical', 'string', 'post', 'hierarchical');
    $atualizar->Set_AdicionarCampo(true, 'has_archive', 'string', 'post', 'has_archive');
    $atualizar->Set_AdicionarCampo(true, 'rewrite', 'string', 'post', 'rewrite');
    $atualizar->Set_AdicionarCampo(true, 'rewrite_slug', 'string', 'post', 'rewrite_slug');
    $atualizar->Set_AdicionarCampo(true, 'query_var', 'string', 'post', 'query_var');
    $atualizar->Set_AdicionarCampo(true, 'labels_name', 'string', 'post', 'labels_name');
    $atualizar->Set_AdicionarCampo(true, 'labels_singular_name', 'string', 'post', 'labels_singular_name');
    $atualizar->Set_AdicionarCampo(true, 'labels_add_new', 'string', 'post', 'labels_add_new');
    $atualizar->Set_AdicionarCampo(true, 'labels_add_new_item', 'string', 'post', 'labels_add_new_item');
    $atualizar->Set_AdicionarCampo(true, 'labels_edit_item', 'string', 'post', 'labels_edit_item');
    $atualizar->Set_AdicionarCampo(true, 'labels_new_item', 'string', 'post', 'labels_new_item');
    $atualizar->Set_AdicionarCampo(true, 'labels_view_item', 'string', 'post', 'labels_view_item');
    $atualizar->Set_AdicionarCampo(true, 'labels_search_items', 'string', 'post', 'labels_search_items');
    $atualizar->Set_AdicionarCampo(true, 'labels_not_found', 'string', 'post', 'labels_not_found');
    $atualizar->Set_AdicionarCampo(true, 'labels_not_found_in_trash', 'string', 'post', 'labels_not_found_in_trash');
    $atualizar->Set_AdicionarCampo(true, 'labels_all_items', 'string', 'post', 'labels_all_items');
    $atualizar->Set_AdicionarCampo(true, 'labels_archives', 'string', 'post', 'labels_archives');
    $atualizar->Set_AdicionarCampo(true, 'labels_attributes', 'string', 'post', 'labels_attributes');
    $atualizar->Set_AdicionarCampo(true, 'labels_insert_into_item', 'string', 'post', 'labels_insert_into_item');
    $atualizar->Set_AdicionarCampo(true, 'labels_uploaded_to_this_item', 'string', 'post', 'labels_uploaded_to_this_item');
    $atualizar->Set_AdicionarCampo(true, 'labels_featured_image', 'string', 'post', 'labels_featured_image');
    $atualizar->Set_AdicionarCampo(true, 'labels_set_featured_image', 'string', 'post', 'labels_set_featured_image');
    $atualizar->Set_AdicionarCampo(true, 'labels_remove_featured_image', 'string', 'post', 'labels_remove_featured_image');
    $atualizar->Set_AdicionarCampo(true, 'labels_use_featured_image', 'string', 'post', 'labels_use_featured_image');
    $atualizar->Set_AdicionarCampo(true, 'labels_menu_name', 'string', 'post', 'labels_menu_name');
    $atualizar->Set_AdicionarCampo(true, 'labels_filter_items_list', 'string', 'post', 'labels_filter_items_list');
    $atualizar->Set_AdicionarCampo(true, 'labels_items_list_navigation', 'string', 'post', 'labels_items_list_navigation');
    $atualizar->Set_AdicionarCampo(true, 'labels_items_list', 'string', 'post', 'labels_items_list');
    $atualizar->Set_AdicionarCampo(true, 'labels_name_admin_bar', 'string', 'post', 'labels_name_admin_bar');
    $atualizar->Set_AdicionarCampo(true, 'supports_title', 'string', 'post', 'supports_title');
    $atualizar->Set_AdicionarCampo(true, 'supports_editor', 'string', 'post', 'supports_editor');
    $atualizar->Set_AdicionarCampo(true, 'supports_author', 'string', 'post', 'supports_author');
    $atualizar->Set_AdicionarCampo(true, 'supports_thumbnail', 'string', 'post', 'supports_thumbnail');
    $atualizar->Set_AdicionarCampo(true, 'supports_excerpt', 'string', 'post', 'supports_excerpt');
    $atualizar->Set_AdicionarCampo(true, 'supports_trackbacks', 'string', 'post', 'supports_trackbacks');
    $atualizar->Set_AdicionarCampo(true, 'supports_custom_fields', 'string', 'post', 'supports_custom_fields');
    $atualizar->Set_AdicionarCampo(true, 'supports_comments', 'string', 'post', 'supports_comments');
    $atualizar->Set_AdicionarCampo(true, 'supports_revisions', 'string', 'post', 'supports_revisions');
    $atualizar->Set_AdicionarCampo(true, 'supports_page_attributes', 'string', 'post', 'supports_page_attributes');
    $atualizar->Set_AdicionarCampo(true, 'supports_post_formats', 'string', 'post', 'supports_post_formats');
    $atualizar->Set_RetornarParaPagina('studiopreview','post-type', 'editar-post-type', 'id_post_type=' . $_POST['id_post_type']);
    $atualizar->Executar();