<?php

     $tabela_post_type = new \Spw\Componentes\Mysql\CriarTabela();
     $tabela_post_type->Set_NomeDaTabela('spw_post_type');
     $tabela_post_type->Set_AdicionarColuna("id_post_type INT(11) NOT NULL AUTO_INCREMENT");
     $tabela_post_type->Set_AdicionarColuna("time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP");
     $tabela_post_type->Set_AdicionarColuna("lixeira CHAR(1) NOT NULL DEFAULT 'Y'");
     $tabela_post_type->Set_AdicionarColuna("post_type VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("public CHAR(1) NULL DEFAULT 1");
     $tabela_post_type->Set_AdicionarColuna("publicly_queryable CHAR(1) NULL DEFAULT 1");
     $tabela_post_type->Set_AdicionarColuna("show_ui CHAR(1) NULL DEFAULT 1");
     $tabela_post_type->Set_AdicionarColuna("show_in_menu CHAR(1) NULL DEFAULT 1");
     $tabela_post_type->Set_AdicionarColuna("show_in_nav_menus CHAR(1) NULL DEFAULT 1");
     $tabela_post_type->Set_AdicionarColuna("show_in_admin_bar CHAR(1) NULL DEFAULT 1");
     $tabela_post_type->Set_AdicionarColuna("menu_position INT(11) NULL");
     $tabela_post_type->Set_AdicionarColuna("menu_icon VARCHAR(500) NULL");
     $tabela_post_type->Set_AdicionarColuna("capability_type VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("hierarchical CHAR(1) NULL DEFAULT 0");
     $tabela_post_type->Set_AdicionarColuna("has_archive CHAR(1) NULL DEFAULT 1");
     $tabela_post_type->Set_AdicionarColuna("rewrite CHAR(1) NULL DEFAULT 1");
     $tabela_post_type->Set_AdicionarColuna("rewrite_slug VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("query_var CHAR(1) NULL DEFAULT 1");
     $tabela_post_type->Set_AdicionarColuna("labels_name VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_singular_name VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_add_new VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_add_new_item VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_edit_item VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_new_item VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_view_item VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_view_items VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_search_items VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_not_found VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_not_found_in_trash VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_parent_item_colon VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_all_items VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_archives VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_attributes VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_insert_into_item VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_uploaded_to_this_item VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_featured_image VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_set_featured_image VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_remove_featured_image VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_use_featured_image VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_menu_name VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_filter_items_list VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_items_list_navigation VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_items_list VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("labels_name_admin_bar VARCHAR(100) NULL");
     $tabela_post_type->Set_AdicionarColuna("supports_title CHAR(1) NULL DEFAULT 0");
     $tabela_post_type->Set_AdicionarColuna("supports_editor CHAR(1) NULL DEFAULT 0");
     $tabela_post_type->Set_AdicionarColuna("supports_author CHAR(1) NULL DEFAULT 0");
     $tabela_post_type->Set_AdicionarColuna("supports_thumbnail CHAR(1) NULL DEFAULT 0");
     $tabela_post_type->Set_AdicionarColuna("supports_excerpt CHAR(1) NULL DEFAULT 0");
     $tabela_post_type->Set_AdicionarColuna("supports_trackbacks CHAR(1) NULL DEFAULT 0");
     $tabela_post_type->Set_AdicionarColuna("supports_custom_fields CHAR(1) NULL DEFAULT 0");
     $tabela_post_type->Set_AdicionarColuna("supports_comments CHAR(1) NULL DEFAULT 0");
     $tabela_post_type->Set_AdicionarColuna("supports_revisions CHAR(1) NULL DEFAULT 0");
     $tabela_post_type->Set_AdicionarColuna("supports_page_attributes CHAR(1) NULL DEFAULT 0");
     $tabela_post_type->Set_AdicionarColuna("supports_post_formats CHAR(1) NULL DEFAULT 0");
     $tabela_post_type->Set_ChavePrimaria('id_post_type');
     $tabela_post_type->Executar();